###
GET https://api-colaborator-employees.herokuapp.com/api/employees

###
POST https://api-colaborator-employees.herokuapp.com/api/employees
Content-Type: application/json

{
  "name":"Juan López",
  "position":"Snr. Back-end",
  "office":"España",
  "salary":"S/.5000"
}

###
Get https://api-colaborator-employees.herokuapp.com/api/employees/5f67d52ec8fcdc2c8efa6b26

###

DELETE  https://api-colaborator-employees.herokuapp.com/api/employees/5f67d52ec8fcdc2c8efa6b26

###
PUT  https://api-colaborator-employees.herokuapp.com/api/employees/5f67d52ec8fcdc2c8efa6b26
Content-Type: application/json

{
  "salary":1500
}